version: '3.8'

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: rag_pgvector
    environment:
      POSTGRES_DB: ${PGVECTOR_DB_NAME}
      POSTGRES_USER: ${PGVECTOR_USER}
      POSTGRES_PASSWORD: ${PGVECTOR_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./scripts/setup_pgvector.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGVECTOR_USER} -d ${PGVECTOR_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rag_network

  app_rag:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_app
    env_file:
      - .env
    volumes:
      - ./:/app           # Mapeo de c√≥digo
      - ./data:/app/data
    ports:
      - "8001:8000"
    depends_on:
      pgvector:
        condition: service_healthy
    command: tail -f /dev/null
    networks:
      - rag_network

volumes:
  pgvector_data:
  rag_data:
  # BORRADO: huggingface_cache:

networks:
  rag_network:
    driver: bridge